export const items = {
  EnPleinAir: [
    {
      id: 1,
      username: "Marie-Joëlle",
      img: "/images/excursion.jpg",
      title: "Excursion de fin d’année",
      date: "Mercredi 7 juin 2023 de 12 H 30 à 14 H 30",
      place:
        "Escale déjeuner - Débarquement à la guinguette 'Chez Gégène' à Joinville-le-Pont",
      desc: "Croisière commentée : Les bords de Marne au pays des guinguettes",
      category: "EnPleinAir",
      price: 10,
      rating: 5,
      programme:
        "La croisière commence dans le port de l’Arsenal : après avoir passé l’écluse de la Bastille, superbe point de vue sur Notre Dame de Paris et découverte des quartiers de l'est de Paris : Bercy, la grande bibliothèque de France... Au confluent de la Marne, Chinagora, le nouveau centre chinois marque la limite du paysage urbain. Tranquillement, le bateau remonte la Marne en passant l'écluse Saint-Maurice, lieu d'enfance de Delacroix, l'île du Moulin-Brulé et l'île aux Corbeaux. Laissant l'île Fanac, nous entrerons au pays des guinguettes : Gégène, Le P’tit Robinson, l'ancien bal Convert et le Verger à Nogent. Après avoir longé les îles des Loups et l'île d'Amour, le bateau fait demi-tour à Bry-sur-Marne et accoste pour une escale à l'heure du déjeuner face à la mythique guinguette 'Chez Gégène' à Joinville-le-Pont où nous prendrons notre repas. L'après-midi, nous reviendrons vers Paris dans une ambiance musette animée par notre accordéoniste, en découvrant de superbes demeures et des paysages protégés peints notamment par Paul Cézanne, Daubigny, Corot, etc. RENDEZ-VOUS : à 8 H 45 précises à l'embarcadère CANAUXRAMA au port de l’Arsenal, face au 50 Bd de la Bastille Paris 12ème – Métro Bastille - Sortie 'Port de l’Arsenal'. Retour vers 17 heures au port de l’Arsenal",
      inscription: "oui",
      keywords: "croisière, Marne, guinguettes, Paris, excursion",
    },
    {
      id: 2,
      username: "Marie-Joëlle",
      img: "/images/Sortiesculturelles.jpg",
      title: "Sorties culturelles",
      date: "Jeudi 14h",
      place: "Piscine de Saint-Mandé",
      description: "Activités hebdomadaires",
      category: "EnPleinAir",
      price: 10,
      rating: 5,
      programme: "Programme non spécifié",
      inscription: "non",
      keywords:
        "sorties culturelles, activités hebdomadaires, Piscine de Saint-Mandé",
    },
    {
      id: 3,
      username: "Marie-Joëlle",
      img: "/images/marche.jpg",
      title: "Marche",
      date: "Jeudi 14h",
      place: "Piscine de Saint-Mandé",
      description: "Activités hebdomadaires",
      category: "EnPleinAir",
      price: 10,
      rating: 5,
      programme: "Programme non spécifié",
      inscription: "non",
      keywords: "marche, activités hebdomadaires, Piscine de Saint-Mandé",
    },
    // Autres activités de la catégorie EnPleinAir
  ],
  Aquatique: [
    {
      id: 4,
      username: "Marie-Joëlle",
      img: "/images/aquagym.jpg",
      title: "Aquagym",
      date: "Jeudi 14h",
      place: "Piscine de Saint-Mandé",
      description: "Activités hebdomadaires à la piscine de Saint-Mandé",
      category: "Activité hebdomadaire",
      price: "gratuit",
      rating: 5,
      programme: "Programme non spécifié",
      inscription: "oui",
      keywords: "aquagym, activités hebdomadaires, Piscine de Saint-Mandé",
    },
    {
      id: 5,
      username: "Marie-Joëlle",
      img: "/images/aquagym.jpg",
      title: "Aquagym",
      date: "Jeudi 14h",
      place: "Piscine de Saint-Mandé",
      description: "Activités hebdomadaires à la piscine de Saint-Mandé",
      category: "Activité hebdomadaire",
      price: "gratuit",
      rating: 5,
      programme: "Programme non spécifié",
      inscription: "oui",
      keywords: "aquagym, activités hebdomadaires, Piscine de Saint-Mandé",
    },
    {
      id: 6,
      username: "Marie-Joëlle",
      img: "/images/aquagym.jpg",
      title: "Aquagym",
      date: "Jeudi 14h",
      place: "Piscine de Saint-Mandé",
      description: "Activités hebdomadaires à la piscine de Saint-Mandé",
      category: "Activité hebdomadaire",
      price: "gratuit",
      rating: 5,
      programme: "Programme non spécifié",
      inscription: "oui",
      keywords: "aquagym, activités hebdomadaires, Piscine de Saint-Mandé",
    },
    // Autres activités de la catégorie Aquatique
  ],
  Sorties: [
    {
      id: 7,
      username: "Marie-Joëlle",
      img: "/images/cinema.jpg",
      title: "Débats cinéma",
      date: "Mercredi 16h",
      place: "Piscine de Saint-Mandé",
      description: "Sans inscription",
      category: "Activités hebdomadaires",
      price: 10,
      rating: 5,
      programme: "Programme non spécifié",
      inscription: "non",
      keywords:
        "débats cinéma, activités hebdomadaires, Piscine de Saint-Mandé",
    },
    {
      id: 8,
      username: "Marie-Joëlle",
      img: "/images/gouter.jpg",
      title: "Goûter",
      date: "Jeudi 14h",
      place: "Piscine de Saint-Mandé",
      description: "Activités hebdomadaires (les jeudis)",
      category: "Activité hebdomadaire",
      price: 10,
      rating: 5,
      programme: "Programme non spécifié",
      inscription: "non",
      keywords: "goûter, activités hebdomadaires, Piscine de Saint-Mandé",
    },
    // Autres activités de la catégorie Rencontre
  ],
  LoisirsCreatifs: [
    {
      id: 12,
      username: "Marie-Joëlle",
      img: "/images/artflorale.jpg",
      title: "Art floral",
      date: "Lundi 14h",
      place:
        "Centre CRESCO Salle Bruno Cremer - 4 avenue Pasteur 94160 SAINT-MANDÉ",
      description: "L'art traditionnel de l'arrangement floral japonais",
      category: "Activité hebdomadaire",
      price: 20,
      rating: 5,
      programme:
        "Arranger des fleurs est le résultat de l’étude de nombreux aspects, mais quand les personnes prennent place devant les végétaux et les considèrent le cœur plein d’indulgence, ils arborent un visage plus que beau, reflet du changement qui s’opère en eux",
      inscription: "oui",
      keywords:
        "art floral, arrangement floral, activités hebdomadaires, SAINT-MANDÉ",
    },
    {
      id: 13,
      username: "Marie-Joëlle",
      img: "/images/cercle.jpg",
      title: "Cercle de lecture",
      date: "Mardi 14h",
      place:
        "Centre CRESCO Salle Bruno Cremer - 4 avenue Pasteur 94160 SAINT-MANDÉ",
      description:
        "Vous enrichirez vos connaissances et votre appréciation du monde qui vous entoure",
      category: "Activité hebdomadaire",
      price: "gratuit",
      rating: 5,
      programme:
        "Grâce aux discussions approfondies sur un livre en particulier ainsi que les différents points de vue des membres du club, vous enrichirez vos connaissances et votre appréciation du monde qui vous entoure. Vous serez plus enclin à apprécier les autres cultures, non seulement à travers le livre, mais aussi à travers les échanges entre les membres qui peuvent avoir des parcours différents",
      inscription: "non",
      keywords:
        "cercle de lecture, discussion de livres, activités hebdomadaires, SAINT-MANDÉ",
    },
    
  ],
  Theatre: [
    {
      id: 13,
      username: "Marie-Joëlle",
      img: "/images/artflorale.jpg",
      title: "Art floral",
      date: "Lundi 14h",
      place:
        "Centre CRESCO Salle Bruno Cremer - 4 avenue Pasteur 94160 SAINT-MANDÉ",
      description: "L'art traditionnel de l'arrangement floral japonais",
      category: "Activité hebdomadaire",
      price: 20,
      rating: 5,
      programme:
        "Arranger des fleurs est le résultat de l’étude de nombreux aspects, mais quand les personnes prennent place devant les végétaux et les considèrent le cœur plein d’indulgence, ils arborent un visage plus que beau, reflet du changement qui s’opère en eux",
      inscription: "oui",
      keywords:
        "art floral, arrangement floral, activités hebdomadaires, SAINT-MANDÉ",
    },
    {
      id: 14,
      username: "Marie-Joëlle",
      img: "/images/cercle.jpg",
      title: "Cercle de lecture",
      date: "Mardi 14h",
      place:
        "Centre CRESCO Salle Bruno Cremer - 4 avenue Pasteur 94160 SAINT-MANDÉ",
      description:
        "Vous enrichirez vos connaissances et votre appréciation du monde qui vous entoure",
      category: "Activité hebdomadaire",
      price: "gratuit",
      rating: 5,
      programme:
        "Grâce aux discussions approfondies sur un livre en particulier ainsi que les différents points de vue des membres du club, vous enrichirez vos connaissances et votre appréciation du monde qui vous entoure. Vous serez plus enclin à apprécier les autres cultures, non seulement à travers le livre, mais aussi à travers les échanges entre les membres qui peuvent avoir des parcours différents",
      inscription: "non",
      keywords:
        "cercle de lecture, discussion de livres, activités hebdomadaires, SAINT-MANDÉ",
    },
    
  ],
};
