export const dataAdherents = [
    {
        id: 1,
        name: 'Dupont',
        surname: 'Jean',
        mail: 'jean.dupont@example.com',
        phone: '01 23 45 67 89',
        adress: '123 rue de la Liberté',
        complement: '',
        cp: '75001',
        city: 'Paris',
    },
    {
        id: 2,
        name: 'Martin',
        surname: 'Marie',
        mail: 'marie.martin@example.com',
        phone: '06 12 34 56 78',
        adress: '456 avenue des Fleurs',
        complement: '',
        cp: '69002',
        city: 'Lyon',
    },
    {
        id: 3,
        name: 'Dubois',
        surname: 'Pierre',
        mail: 'pierre.dubois@example.com',
        phone: '05 45 67 89 01',
        adress: '789 chemin du Soleil',
        complement: '',
        cp: '33000',
        city: 'Bordeaux',
    },
    {
        id: 4,
        name: 'Moreau',
        surname: 'Lucie',
        mail: 'lucie.moreau@example.com',
        phone: '07 23 45 67 89',
        adress: '10 rue de la Paix',
        complement: '',
        cp: '69003',
        city: 'Lyon',
    },
    {
        id: 5,
        name: 'Leroy',
        surname: 'Thomas',
        mail: 'thomas.leroy@example.com',
        phone: '03 33 33 33 33',
        adress: '15 avenue Victor Hugo',
        complement: '',
        cp: '75002',
        city: 'Paris',
    },
    {
        id: 6,
        name: 'Lefevre',
        surname: 'Sophie',
        mail: 'sophie.lefevre@example.com',
        phone: '02 44 55 66 77',
        adress: '25 rue Saint-Jacques',
        complement: '',
        cp: '33001',
        city: 'Bordeaux',
    },
    {
        id: 7,
        name: 'Martin',
        surname: 'Antoine',
        mail: 'antoine.martin@example.com',
        phone: '09 87 65 43 21',
        adress: '20 avenue des Champs-Élysées',
        complement: '',
        cp: '75008',
        city: 'Paris',
    },
];
